// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
    /**
     * title field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = AboutTextSlice | InfoSectionSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = PageDocument;
/**
 * Primary content in AboutText → Primary
 *
 */
interface AboutTextSliceDefaultPrimary {
    /**
     * Title field in *AboutText → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: about_text.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *AboutText → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: about_text.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for AboutText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `AboutText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutTextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AboutTextSliceDefaultPrimary>, never>;
/**
 * Slice variation for *AboutText*
 *
 */
type AboutTextSliceVariation = AboutTextSliceDefault;
/**
 * AboutText Shared Slice
 *
 * - **API ID**: `about_text`
 * - **Description**: `AboutText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutTextSlice = prismicT.SharedSlice<"about_text", AboutTextSliceVariation>;
/**
 * Primary content in InfoSection → Primary
 *
 */
interface InfoSectionSliceDefaultPrimary {
    /**
     * Title field in *InfoSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is an information section
     * - **API ID Path**: info_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *InfoSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: info_section.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for InfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `InfoSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<InfoSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *InfoSection*
 *
 */
type InfoSectionSliceVariation = InfoSectionSliceDefault;
/**
 * InfoSection Shared Slice
 *
 * - **API ID**: `info_section`
 * - **Description**: `InfoSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoSectionSlice = prismicT.SharedSlice<"info_section", InfoSectionSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, AboutTextSliceDefaultPrimary, AboutTextSliceDefault, AboutTextSliceVariation, AboutTextSlice, InfoSectionSliceDefaultPrimary, InfoSectionSliceDefault, InfoSectionSliceVariation, InfoSectionSlice };
    }
}
