// Code generated by Slice Machine. DO NOT EDIT.

import AboutText from './AboutText';
import InfoSection from './InfoSection';

export {
	AboutText,
	InfoSection,
};

export const components = {
	about_text: AboutText,
	info_section: InfoSection,
};
