// Code generated by Slice Machine. DO NOT EDIT.

import AboutText from './AboutText';
import AnotherSlice from './AnotherSlice';
import InfoSection from './InfoSection';
import NavigationItem from './NavigationItem';

export {
	AboutText,
	AnotherSlice,
	InfoSection,
	NavigationItem,
};

export const components = {
	about_text: AboutText,
	another_slice: AnotherSlice,
	info_section: InfoSection,
	navigation_item: NavigationItem,
};
